# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-18 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=45)),
                ('port', models.IntegerField(max_length=10)),
                ('status', models.IntegerField(choices=[(1, '\u672a\u77e5'), (2, '\u5728\u7ebf'), (3, '\u79bb\u7ebf')], default=1)),
            ],
        ),
    ]
