# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-18 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubstatus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='port',
            field=models.IntegerField(),
        ),
    ]
