# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-19 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubstatus', '0002_auto_20180718_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='server_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
