# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-07-20 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubstatus', '0003_instance_server_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='env_flag',
            field=models.IntegerField(choices=[(1, '\u7ebf\u4e0anginx'), (2, '\u6d4b\u8bd5nginx'), (3, '\u81ea\u5b9a\u4e49')], default=3),
        ),
    ]
